import { Head, router, useForm } from '@inertiajs/react';
import { CheckCircle2, CircleAlert, Layers3, Network, Plus, Trash2 } from 'lucide-react';
import { useState } from 'react';

export default function RpsShow({ rps, cpls, cpmks, subCpmks, materials, weeks, progress }: any) {
    const [openWeek, setOpenWeek] = useState<number|null>(null);
    const mappingForm = useForm({ mappings: Object.fromEntries(cpmks.map((c:any)=>[c.id,c.cpl_ids])) });
    const subForm = useForm({ rps_cpmk_id: cpmks[0]?.id ?? '', description: '', bloom_level: '' });
    const materialForm = useForm({ rps_sub_cpmk_id: '', title: '', description: '' });
    const toggle = (cpmkId:string,cplId:string) => { const cur=mappingForm.data.mappings[cpmkId]??[]; mappingForm.setData('mappings',{...mappingForm.data.mappings,[cpmkId]:cur.includes(cplId)?cur.filter((x:string)=>x!==cplId):[...cur,cplId]}); };

    return <><Head title={`RPS ${rps.course_name}`} /><div className="p-4 md:p-6">
        <div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="text-xs font-bold uppercase tracking-wider text-teal-700">Workspace OBE</div><h1 className="mt-1 text-2xl font-bold">{rps.course_name}</h1><p className="mt-1 text-sm text-slate-500">{rps.official_code||rps.system_code} · {rps.credits} SKS · {rps.academic_year} {rps.academic_semester}</p></div><div className="sim-surface w-full max-w-md rounded-2xl p-4"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase text-slate-400">Progress OBE</div><div className="mt-1 text-2xl font-extrabold">{progress.percent}%</div></div></div><div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-teal-700 to-cyan-400" style={{width:`${progress.percent}%`}} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs">{progress.checks.map((x:any)=><div key={x.label} className="flex items-center gap-2">{x.done?<CheckCircle2 className="size-3.5 text-emerald-600" />:<CircleAlert className="size-3.5 text-amber-500" />}<span>{x.label}</span></div>)}</div></div></div>

        <div className="mt-6 space-y-5">
            <section className="sim-surface rounded-2xl p-5"><div className="flex items-center gap-2"><Network className="size-5 text-teal-700" /><h2 className="font-bold">1. Pemetaan CPMK → CPL</h2></div><p className="mt-1 text-sm text-slate-500">Hanya CPL resmi mata kuliah yang dapat dipilih.</p><form onSubmit={(e)=>{e.preventDefault();mappingForm.put(`/rps/${rps.id}/cpmk-cpl`,{preserveScroll:true})}} className="mt-5 space-y-3">{cpmks.map((c:any)=><div key={c.id} className="rounded-xl border border-slate-100 bg-white/55 p-4"><div className="font-bold text-teal-800">{c.code}</div><div className="mt-1 text-sm text-slate-600">{c.description}</div><div className="mt-3 flex flex-wrap gap-2">{cpls.map((p:any)=>{const checked=(mappingForm.data.mappings[c.id]??[]).includes(p.id);return <label key={p.id} className={`cursor-pointer rounded-full border px-3 py-1.5 text-xs font-bold ${checked?'border-teal-300 bg-teal-100 text-teal-800':'border-slate-200 bg-white/70 text-slate-500'}`}><input type="checkbox" className="sr-only" checked={checked} onChange={()=>toggle(c.id,p.id)} />{p.code}</label>})}</div></div>)}<button className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Simpan Pemetaan</button></form></section>

            <div className="grid gap-5 xl:grid-cols-2"><section className="sim-surface rounded-2xl p-5"><h2 className="font-bold">2. Sub-CPMK</h2><form onSubmit={(e)=>{e.preventDefault();subForm.post(`/rps/${rps.id}/sub-cpmk`,{preserveScroll:true,onSuccess:()=>subForm.reset('description','bloom_level')})}} className="mt-4 rounded-xl border border-teal-100 bg-teal-50/35 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_120px]"><select value={subForm.data.rps_cpmk_id} onChange={(e)=>subForm.setData('rps_cpmk_id',e.target.value)} className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm">{cpmks.map((c:any)=><option key={c.id} value={c.id}>{c.code}</option>)}</select><select value={subForm.data.bloom_level} onChange={(e)=>subForm.setData('bloom_level',e.target.value)} className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm"><option value="">Bloom</option>{['C1','C2','C3','C4','C5','C6'].map(x=><option key={x}>{x}</option>)}</select></div><textarea value={subForm.data.description} onChange={(e)=>subForm.setData('description',e.target.value)} className="mt-3 min-h-24 w-full rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" placeholder="Deskripsi Sub-CPMK" /><button className="mt-3 inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white"><Plus className="size-4" />Tambah</button></form><div className="mt-4 space-y-2">{subCpmks.map((s:any)=><div key={s.id} className="flex items-start justify-between rounded-xl border border-slate-100 bg-white/60 p-4"><div><div className="font-bold text-teal-800">{s.code} {s.bloom_level&&<span className="ml-2 text-xs text-sky-700">{s.bloom_level}</span>}</div><p className="mt-1 text-sm text-slate-600">{s.description}</p></div><button onClick={()=>router.delete(`/rps/${rps.id}/sub-cpmk/${s.id}`,{preserveScroll:true})}><Trash2 className="size-4 text-slate-300 hover:text-rose-600" /></button></div>)}</div></section>

            <section className="sim-surface rounded-2xl p-5"><div className="flex items-center justify-between"><div><div className="flex items-center gap-2"><Layers3 className="size-5 text-teal-700" /><h2 className="font-bold">3. Bahan Kajian</h2></div><p className="mt-1 text-sm text-slate-500">Tambah manual atau ambil dari silabus.</p></div><button onClick={()=>router.post(`/rps/${rps.id}/materials/import-syllabus`,{}, {preserveScroll:true})} className="rounded-xl border border-teal-200 bg-teal-50 px-3 py-2 text-xs font-bold text-teal-700">Ambil dari Silabus</button></div><form onSubmit={(e)=>{e.preventDefault();materialForm.post(`/rps/${rps.id}/materials`,{preserveScroll:true,onSuccess:()=>materialForm.reset()})}} className="mt-4 rounded-xl border border-teal-100 bg-teal-50/35 p-4"><select value={materialForm.data.rps_sub_cpmk_id} onChange={(e)=>materialForm.setData('rps_sub_cpmk_id',e.target.value)} className="w-full rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm"><option value="">Tanpa Sub-CPMK khusus</option>{subCpmks.map((s:any)=><option key={s.id} value={s.id}>{s.code}</option>)}</select><input value={materialForm.data.title} onChange={(e)=>materialForm.setData('title',e.target.value)} className="mt-3 w-full rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" placeholder="Judul bahan kajian" /><button className="mt-3 inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white"><Plus className="size-4" />Tambah</button></form><div className="mt-4 max-h-72 space-y-2 overflow-y-auto">{materials.map((m:any)=><div key={m.id} className="rounded-xl border border-slate-100 bg-white/60 p-4"><div className="font-semibold">{m.title}</div><div className="mt-1 text-[10px] uppercase text-slate-400">{m.source_type}</div></div>)}</div></section></div>

            <section className="sim-surface rounded-2xl p-5"><h2 className="font-bold">4. Rencana 16 Pertemuan</h2><p className="mt-1 text-sm text-slate-500">Klik minggu untuk edit. UTS minggu 8, UAS minggu 16.</p><div className="mt-5 grid gap-2 sm:grid-cols-4 lg:grid-cols-8 xl:grid-cols-16">{weeks.map((w:any)=>{const filled=w.is_exam||w.rps_sub_cpmk_id||w.material_text||w.learning_method;return <button key={w.week_number} type="button" onClick={()=>setOpenWeek(openWeek===w.week_number?null:w.week_number)} className={`rounded-xl border p-3 text-center ${w.is_exam?'border-amber-200 bg-amber-50 text-amber-800':filled?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-slate-200 bg-white/60 text-slate-600'}`}><div className="text-xs font-bold">{w.week_number}</div><div className="mt-1 text-[10px]">{w.exam_type||(filled?'Terisi':'Kosong')}</div></button>})}</div>{openWeek&&<WeekEditor rpsId={rps.id} week={weeks.find((w:any)=>w.week_number===openWeek)} subCpmks={subCpmks} />}</section>
        </div>
    </div></>;
}

function WeekEditor({ rpsId, week, subCpmks }: any) {
    const form=useForm({rps_sub_cpmk_id:week.rps_sub_cpmk_id??'',material_text:week.material_text??'',learning_method:week.learning_method??'',learning_activity:week.learning_activity??'',assessment_indicator:week.assessment_indicator??'',assessment_method:week.assessment_method??'',assessment_weight:week.assessment_weight??'',reference_text:week.reference_text??''});
    return <form onSubmit={(e)=>{e.preventDefault();form.put(`/rps/${rpsId}/weeks/${week.week_number}`,{preserveScroll:true})}} className="mt-5 rounded-2xl border border-teal-100 bg-teal-50/30 p-5"><h3 className="font-bold">Minggu {week.week_number} {week.exam_type?`· ${week.exam_type}`:''}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><select value={form.data.rps_sub_cpmk_id} onChange={(e)=>form.setData('rps_sub_cpmk_id',e.target.value)} className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm"><option value="">Pilih Sub-CPMK</option>{subCpmks.map((s:any)=><option key={s.id} value={s.id}>{s.code}</option>)}</select><input value={form.data.learning_method} onChange={(e)=>form.setData('learning_method',e.target.value)} placeholder="Metode pembelajaran" className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" /><textarea value={form.data.material_text} onChange={(e)=>form.setData('material_text',e.target.value)} placeholder="Materi/Bahan Kajian" className="min-h-20 rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm md:col-span-2" /><textarea value={form.data.learning_activity} onChange={(e)=>form.setData('learning_activity',e.target.value)} placeholder="Aktivitas pembelajaran" className="min-h-20 rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm md:col-span-2" /><textarea value={form.data.assessment_indicator} onChange={(e)=>form.setData('assessment_indicator',e.target.value)} placeholder="Indikator asesmen" className="min-h-20 rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" /><input value={form.data.assessment_method} onChange={(e)=>form.setData('assessment_method',e.target.value)} placeholder="Metode asesmen" className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" /><input type="number" min="0" max="100" value={form.data.assessment_weight} onChange={(e)=>form.setData('assessment_weight',e.target.value)} placeholder="Bobot %" className="rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm" /><textarea value={form.data.reference_text} onChange={(e)=>form.setData('reference_text',e.target.value)} placeholder="Referensi" className="min-h-16 rounded-xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm md:col-span-2" /></div><button className="mt-4 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Simpan Minggu {week.week_number}</button></form>;
}

RpsShow.layout = { breadcrumbs: [{ title: 'RPS Saya', href: '/rps' }, { title: 'Workspace OBE', href: '#' }] };
